
services:
  database:
    image: postgres:alpine
    container_name: postgres-db-3-final
    hostname: database
    volumes:
      - postgres_data_3_final:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=queso
      - POSTGRES_DB=django

  backend:
    container_name: django-backend-final
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=queso
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
    depends_on:
      - database

volumes:
  postgres_data_3_final: